# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    role_hierarchy:
        ROLE_USER:
          - ABILITY_USER_OWNER
          - ABILITY_USER_UPDATE
          - ABILITY_USER_DELETE
          - ABILITY_MESSAGE_OWNER
          - ABILITY_MESSAGE_UPDATE
          - ABILITY_MESSAGE_DELETE
          - ABILITY_INSTAGRAM_ACCOUNT_OWNER
          - ABILITY_INSTAGRAM_ACCOUNT_UPDATE
          - ABILITY_INSTAGRAM_ACCOUNT_DELETE
          - ABILITY_FACEBOOK_POST_OWNER
          - ABILITY_FACEBOOK_POST_UPDATE
          - ABILITY_FACEBOOK_POST_DELETE
          - ABILITY_INSTAGRAM_POST_OWNER
          - ABILITY_INSTAGRAM_POST_UPDATE
          - ABILITY_INSTAGRAM_POST_DELETE
          - ABILITY_GOOGLE_POST_OWNER
          - ABILITY_GOOGLE_POST_UPDATE
          - ABILITY_GOOGLE_POST_DELETE
        ROLE_SUPER_ADMIN: [ROLE_USER]
    encoders:
        SingAppBundle\Entity\User: sha512
    providers:
        app.user_provider:
            id: app.user_provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            anonymous: ~

        main:
            anonymous: ~
            provider: app.user_provider
            logout:
                path:   /logout
                target: /
            guard:
                authenticators:
                    - form_authenticator
        default:
            anonymous: ~