<?php

namespace ReviewsServicesBundle\Repository;

/**
 * ReviewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserReview($date, $userName, $identifier = null)
    {
        return $this->getEntityManager()
            ->getRepository('ReviewsServicesBundle:Reviews')->findOneBy(
                ['created' => $date, 'attribution' => $userName, 'identifier' => $identifier]
            );
    }
}
