<?php

namespace ReviewsServicesBundle\Repository;

/**
 * ServicesSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesSettingRepository extends \Doctrine\ORM\EntityRepository
{
}
