<?php

namespace SingAppBundle\Repository;

/**
 * AdditionalCategoriesBusinessInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalCategoriesBusinessInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
