<?php

namespace SingAppBundle\Repository;

/**
 * BusinessInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
