<?php

namespace SingAppBundle\Repository;
use SingAppBundle\Entity\User;
use Symfony\Component\HttpFoundation\Request;

/**
 * BusinessInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessInfoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCurrentBusiness(Request $request, User $user)
    {
        $qb = $this->createQueryBuilder('entity');

        if ($request->get('business')) {
            $result = $qb
                ->andWhere($qb->expr()->eq('entity.id', $qb->expr()->literal($request->get('business'))))
                ->andWhere($qb->expr()->eq('entity.user', $user->getId()))
                ->getQuery()->setMaxResults(1)->getOneOrNullResult();
        }
        else {
            $result = $qb
                ->where($qb->expr()->eq('entity.user', $user->getId()))
                ->getQuery()->setMaxResults(1)->getOneOrNullResult();
        }

        return $result;
    }
}
