<?php

namespace SingAppBundle\Repository;

/**
 * PhotosBusinessInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotosBusinessInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
