<?php

namespace SingAppBundle\Repository;

use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
use SingAppBundle\Entity\BusinessInfo;
use SingAppBundle\Entity\PinterestAccount;
use SingAppBundle\Entity\PinterestPin;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PinterestPinRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBoard(PinterestAccount $account)
    {
        $em = $this->getEntityManager();

        $sql = 'SELECT DISTINCT board FROM pinterest_pin where pinterest_pin.account_id = ' . $account->getId();

        $statement = $em->getConnection()->prepare($sql);
        $statement->execute();
        $result = $statement->fetchAll();

        $response = [];

        foreach ($result as $board){
            $response[$board['board']] = $board['board'];
        }

        return $response;
    }
}