services:
    app.user.entity_listener:
        class: SingAppBundle\EntityListener\UserEntityListener
        arguments: ['@security.password_encoder', '@security.token_storage']
        tags:
            - { name: doctrine.orm.entity_listener }
    app.set_owner.entity_listener:
        class: SingAppBundle\EntityListener\SetOwnerListener
        arguments: ['@security.token_storage']
        tags:
            - { name: doctrine.orm.entity_listener }
    app.instagram_post.entity_listener:
        class: SingAppBundle\EntityListener\InstagramPostEntityListener
        arguments: ['@app.instagram.service']
        tags:
            - { name: doctrine.orm.entity_listener }