services:
    app.user.entity_listener:
        class: SingAppBundle\EntityListener\UserEntityListener
        arguments: ['@security.password_encoder', '@security.token_storage']
        tags:
            - { name: doctrine.orm.entity_listener }
    app.set_owner.entity_listener:
        class: SingAppBundle\EntityListener\SetOwnerListener
        arguments: ['@security.token_storage']
        tags:
            - { name: doctrine.orm.entity_listener }
    app.set_business.entity_listener:
        class: SingAppBundle\EntityListener\SetBusinessListener
        arguments: ['@session']
        tags:
            - { name: doctrine.orm.entity_listener }
    app.instagram_post.entity_listener:
        class: SingAppBundle\EntityListener\PostEntityListener
        arguments: ['@app.instagram.service', '@app.google.service', '@app.youtube.service',  '@app.linkedin.service', '@app.pinterest.service', '@app.facebook.service']
        tags:
            - { name: doctrine.orm.entity_listener }
    app.media.entity_listener:
        class: SingAppBundle\EntityListener\MediaEntityListener
        arguments: ['@app.photo.service']
        tags:
            - { name: doctrine.orm.entity_listener }
    app.pinterest.entity_listener:
        class: SingAppBundle\EntityListener\PinterestPinEntityListener
        arguments: ['@app.pinterest.service']
        tags:
            - { name: doctrine.orm.entity_listener }
    app.exception.kernel_listener:
        class: SingAppBundle\EntityListener\ExceptionListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }