imports:
    - { resource: listeners.yml }
services:
    form_authenticator:
        class: SingAppBundle\Security\FormAuthenticator
        arguments: ["@router", "@security.password_encoder"]

    app.user_provider:
        class: SingAppBundle\Security\Authentication\AppUserProvider
        arguments: ['@doctrine.orm.entity_manager']

    google_provider:
        class: SingAppBundle\Providers\GoogleCompanies
        arguments:
            $session : '@session'

    facebook_provider:
        class: SingAppBundle\Providers\FacebookCompanies
        arguments:
            $session : '@session'

    instagram_provider:
        class: SingAppBundle\Providers\InstagramBusiness
        arguments:
            $entityManager : '@doctrine.orm.entity_manager'

    app.google.service:
        class: SingAppBundle\Services\GoogleService
        arguments: ['@doctrine.orm.entity_manager']

    app.facebook.service:
        class: SingAppBundle\Services\FacebookService
        arguments: ['%domain%', '@doctrine.orm.entity_manager']

    app.yelp.service:
        class: SingAppBundle\Services\YelpService
        arguments: ['@doctrine.orm.entity_manager']

    app.instagram.service:
        class: SingAppBundle\Services\InstagramService
        arguments: ['@doctrine.orm.entity_manager']

    app.foursquare.service:
        class: SingAppBundle\Services\FoursquareService
        arguments: ['@doctrine.orm.entity_manager']
    app.pinterest.service:
        class: SingAppBundle\Services\PinterestService
        arguments: ['@doctrine.orm.entity_manager']
    app.factual.service:
        class: SingAppBundle\Services\FactualService
        arguments: ['@doctrine.orm.entity_manager']
    app.bing.service:
        class: SingAppBundle\Services\BingService
        arguments: ['@doctrine.orm.entity_manager']
