services:
    google_provider:
        class: SingAppBundle\Providers\GoogleCompanies
        arguments:
            $session : '@session'

    facebook_provider:
        class: SingAppBundle\Providers\FacebookCompanies
        arguments:
            $session : '@session'

    instagram_provider:
        class: SingAppBundle\Providers\InstagramBusiness
        arguments:
            $entityManager : '@doctrine.orm.entity_manager'

    app.google.service:
        class: SingAppBundle\Service\GoogleService

    app.facebook.service:
        class: SingAppBundle\Service\FacebookService

    app.yelp.service:
        class: SingAppBundle\Service\YelpService
